In [17]:
import numpy as np
import pandas as pd
from os import path
import pickle

pd.options.display.max_seq_items = 2000

In [18]:
openfile=open( r"C:\Users\Joseph\Documents\Beamly\TakeHomeTask\beamly_case_study2.pickle", "rb")
df=pickle.load(openfile)
openfile.close()

In [19]:
df.shape

(27091, 13)

In [20]:
df.columns

Index(['date', 'avg_hour', 'min_hour', 'max_hour', 'device_name',
       'productBand', 'avg_price', 'total_products', 'num_orders', 'city',
       'region', 'County', 'Country'],
      dtype='object')

In [21]:
df.head(20)

,date,avg_hour,min_hour,max_hour,device_name,productBand,avg_price,total_products,num_orders,city,region,County,Country
1,2018-07-12,20.0,20,20,Mobile,between20and30,29.950,1.0,1,Redbourn,Hertfordshire,Hertfordshire,England
2,2018-08-05,22.0,22,22,Desktop and Laptop,between20and30,27.950,1.0,1,Bearsden,East Dunbartonshire,NaN,NaN
3,2018-07-13,14.0,14,14,Mobile,between20and30,27.950,1.0,1,Bearsden,East Dunbartonshire,NaN,NaN
5,2018-08-10,19.0,19,19,Tablet,lessThan10,9.950,1.0,1,Bearsden,East Dunbartonshire,NaN,NaN
6,2018-07-12,17.0,17,17,Desktop and Laptop,between20and30,29.950,1.0,1,Greenwich,Greenwich,NaN,NaN
7,2018-07-09,16.0,16,16,Mobile,between20and30,29.950,1.0,1,Greenwich,Greenwich,NaN,NaN
8,2018-07-05,11.0,11,11,Desktop and Laptop,lessThan10,8.990,1.0,1,Greenwich,Greenwich,NaN,NaN
10,2018-08-07,18.0,18,18,Desktop and Laptop,lessThan10,1.990,4.0,1,Greenwich,Greenwich,NaN,NaN
11,2018-08-11,12.0,12,12,Desktop and Laptop,between10and20,19.950,1.0,1,Greenwich,Greenwich,NaN,NaN
12,2018-07-17,12.5,11,14,Tablet,between20and30,26.225,2.0,2,Greenwich,Greenwich,NaN,NaN
13,2018-07-16,13.0,13,13,Mobile,between10and20,14.950,1.0,1,Greenwich,Greenwich,NaN,NaN
16,2018-08-13,15.0,15,15,Mobile,between10and20,19.900,NaN,1,Greenwich,Greenwich,NaN,NaN
17,2018-07-12,15.0,15,15,Desktop and Laptop,lessThan10,1.500,1.0,1,Greenwich,Greenwich,NaN,NaN
19,2018-07-10,16.0,16,16,Mobile,between10and20,19.950,2.0,1,Greenwich,Greenwich,NaN,NaN
20,2018-08-11,15.0,15,15,Mobile,between20and30,22.950,NaN,1,Greenwich,Greenwich,NaN,NaN
21,2018-07-06,6.0,6,6,Desktop and Laptop,between10and20,14.950,1.0,1,Greenwich,Greenwich,NaN,NaN
22,2018-07-09,15.0,15,15,Mobile,lessThan10,1.950,5.0,1,Greenwich,Greenwich,NaN,NaN
23,2018-08-06,19.0,19,19,Desktop and Laptop,lessThan10,2.160,4.0,1,Greenwich,Greenwich,NaN,NaN
24,2018-07-15,22.0,22,22,Mobile,price_missing,NaN,1.0,1,Greenwich,Greenwich,NaN,NaN
25,2018-07-29,12.5,2,23,Mobile,between20and30,25.950,2.0,2,Greenwich,Greenwich,NaN,NaN

#### Note on Nans

Nans exist in the following columns and need to be imputed: avg_price, total_products, County, Country

 Start with something 'easy' or not too important. Want to think about how could impute Country/County, so look to see if city or region can help.

### Impute Country/County

In [22]:
df.groupby(['Country'])['County'].unique().to_dict()

{'England': array(['Hertfordshire', 'Suffolk', 'Worcestershire', 'West Sussex',
        'Lincolnshire', 'Essex', 'North Yorkshire', 'Cornwall', 'Devon',
        'Norfolk', 'Hampshire', 'Buckinghamshire', 'Nottinghamshire',
        'East Sussex', 'Kent', 'Lancashire', 'Staffordshire', 'Bristol',
        'Surrey', 'Cumbria', 'Northumberland', 'Derbyshire',
        'Northamptonshire', 'Gloucestershire', 'Cambridgeshire',
        'Oxfordshire', 'Warwickshire', 'Somerset', 'Wiltshire', 'Dorset',
        'Shropshire', 'Bedfordshire', 'Leicestershire', 'Herefordshire',
        'Rutland'], dtype=object),
 'Scotland': array(['Falkirk', 'East Lothian', 'Fife', 'Clackmannanshire', 'Moray',
        'West Lothian', 'Scottish Borders', 'Aberdeenshire', 'Angus'],
       dtype=object),
 'Wales': array(['Pembrokeshire', 'Conwy', 'Monmouthshire', 'Carmarthenshire',
        'Gwynedd', 'Denbighshire', 'Ceredigion', 'Wrexham', 'Flintshire',
        'Powys'], dtype=object)}

In [23]:
country_city_dict=df.groupby(['Country'])['city'].unique().to_dict()
for i in country_city_dict['England']:
    if i=='Greenwich':
        print(i)

Was thinking of using the city and region to impute a county and country, but looks like that won't work. It's probably easiest to make a new generalised Country as UK, for the sake of this excerise it would be easier. Otherwise you could use an outside source of information to match cities with county and country.

I think the easiest thing to do now would be to replace the missing fields with missing_country and missing_county. Especially as it is not relevant to the problem, which is just to forecast sales no specific to country or county.

In [24]:
from sklearn.preprocessing import Imputer

In [26]:
#imp = Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)
#imp.fit()

In [27]:
df_e=df

In [28]:
df_e['Country']=df['Country'].apply(lambda x: x if pd.notnull(x)==True else 'missing_country')

In [30]:
df_e['County']=df['County'].apply(lambda x: x if pd.notnull(x)==True else 'missing_county')

In [31]:
df_e

,date,avg_hour,min_hour,max_hour,device_name,productBand,avg_price,total_products,num_orders,city,region,County,Country
1,2018-07-12,20.0,20,20,Mobile,between20and30,29.950,1.0,1,Redbourn,Hertfordshire,Hertfordshire,England
2,2018-08-05,22.0,22,22,Desktop and Laptop,between20and30,27.950,1.0,1,Bearsden,East Dunbartonshire,missing_county,missing_country
3,2018-07-13,14.0,14,14,Mobile,between20and30,27.950,1.0,1,Bearsden,East Dunbartonshire,missing_county,missing_country
5,2018-08-10,19.0,19,19,Tablet,lessThan10,9.950,1.0,1,Bearsden,East Dunbartonshire,missing_county,missing_country
6,2018-07-12,17.0,17,17,Desktop and Laptop,between20and30,29.950,1.0,1,Greenwich,Greenwich,missing_county,missing_country
7,2018-07-09,16.0,16,16,Mobile,between20and30,29.950,1.0,1,Greenwich,Greenwich,missing_county,missing_country
8,2018-07-05,11.0,11,11,Desktop and Laptop,lessThan10,8.990,1.0,1,Greenwich,Greenwich,missing_county,missing_country
10,2018-08-07,18.0,18,18,Desktop and Laptop,lessThan10,1.990,4.0,1,Greenwich,Greenwich,missing_county,missing_country
11,2018-08-11,12.0,12,12,Desktop and Laptop,between10and20,19.950,1.0,1,Greenwich,Greenwich,missing_county,missing_country
12,2018-07-17,12.5,11,14,Tablet,between20and30,26.225,2.0,2,Greenwich,Greenwich,missing_county,missing_country
13,2018-07-16,13.0,13,13,Mobile,between10and20,14.950,1.0,1,Greenwich,Greenwich,missing_county,missing_country
16,2018-08-13,15.0,15,15,Mobile,between10and20,19.900,NaN,1,Greenwich,Greenwich,missing_county,missing_country
17,2018-07-12,15.0,15,15,Desktop and Laptop,lessThan10,1.500,1.0,1,Greenwich,Greenwich,missing_county,missing_country
19,2018-07-10,16.0,16,16,Mobile,between10and20,19.950,2.0,1,Greenwich,Greenwich,missing_county,missing_country
20,2018-08-11,15.0,15,15,Mobile,between20and30,22.950,NaN,1,Greenwich,Greenwich,missing_county,missing_country
21,2018-07-06,6.0,6,6,Desktop and Laptop,between10and20,14.950,1.0,1,Greenwich,Greenwich,missing_county,missing_country
22,2018-07-09,15.0,15,15,Mobile,lessThan10,1.950,5.0,1,Greenwich,Greenwich,missing_county,missing_country
23,2018-08-06,19.0,19,19,Desktop and Laptop,lessThan10,2.160,4.0,1,Greenwich,Greenwich,missing_county,missing_country
24,2018-07-15,22.0,22,22,Mobile,price_missing,NaN,1.0,1,Greenwich,Greenwich,missing_county,missing_country
25,2018-07-29,12.5,2,23,Mobile,between20and30,25.950,2.0,2,Greenwich,Greenwich,missing_county,missing_country
26,2018-07-15,13.0,13,13,Mobile,between10and20,15.950,1.0,1,Greenwich,Greenwich,missing_county,missing_country
27,2018-08-04,19.0,19,19,Desktop and Laptop,between20and30,23.450,2.0,2,Greenwich,Greenwich,missing_county,missing_country
29,2018-07-31,16.0,16,16,Desktop and Laptop,lessThan10,6.470,2.0,1,Greenwich,Greenwich,missing_county,missing_country
30,2018-08-07,9.0,9,9,Mobile,between20and30,29.500,1.0,1,Greenwich,Greenwich,missing_county,missing_country
31,2018-08-12,8.0,0,18,Mobile,between20and30,25.450,NaN,3,Greenwich,Greenwich,missing_county,missing_country
32,2018-07-03,20.0,20,20,Tablet,between20and30,21.950,1.0,1,Greenwich,Greenwich,missing_county,missing_country
33,2018-08-01,18.0,18,18,Mobile,between40and50,47.950,1.0,1,Greenwich,Greenwich,missing_county,missing_country
35,2018-08-03,7.0,7,7,Mobile,between10and20,17.950,1.0,1,Greenwich,Greenwich,missing_county,missing_country
36,2018-08-01,21.0,21,21,Mobile,lessThan10,1.990,1.0,1,Greenwich,Greenwich,missing_county,missing_country
37,2018-07-18,17.0,17,17,Mobile,between20and30,27.500,1.0,1,Greenwich,Greenwich,missing_county,missing_country
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32646,2018-07-21,10.0,10,10,Mobile,between10and20,19.950,1.0,1,Broughton,Flintshire,Flintshire,Wales
32647,2018-08-06,11.0,11,11,Desktop and Laptop,between10and20,17.990,1.0,1,Holbeach,Lincolnshire,Lincolnshire,England
32648,2018-07-19,12.0,12,12,Tablet,moreThan50,51.990,1.0,1,Eastchurch,Kent,Kent,England
32649,2018-07-10,14.0,14,14,Mobile,between20and30,22.950,1.0,1,Kingseat,Fife,Fife,Scotland
32650,2018-07-30,19.0,19,19,Mobile,between20and30,24.950,1.0,1,Shildon,Durham,missing_county,missing_country
32651,2018-07-19,15.0,15,15,Mobile,between20and30,22.950,1.0,1,Burham,Kent,Kent,England
32652,2018-08-07,20.0,20,20,Mobile,lessThan10,1.990,1.0,1,Atworth,Wiltshire,Wiltshire,England
32653,2018-08-09,21.0,21,21,Desktop and Laptop,between40and50,42.950,1.0,1,Farndon,Nottinghamshire,Nottinghamshire,England
32654,2018-07-24,17.0,17,17,Tablet,between10and20,12.950,2.0,1,Blythe bridge,Staffordshire,Staffordshire,England
32655,2018-07-04,0.0,0,0,Mobile,between20and30,29.950,1.0,1,Greystoke,Cumbria,Cumbria,England
32656,2018-07-23,15.0,15,15,Mobile,between40and50,41.950,1.0,1,Whitworth,Lancashire,Lancashire,England
32657,2018-08-08,17.0,17,17,Mobile,moreThan50,58.950,NaN,1,Whickham,Gateshead,missing_county,missing_country
32663,2018-07-03,13.0,13,13,Mobile,between10and20,13.500,1.0,1,Abergynolwyn,Gwynedd,Gwynedd,Wales
32664,2018-08-12,12.0,12,12,Tablet,between20and30,22.950,1.0,1,Dalry,Dumfries And Galloway,missing_county,missing_country
32665,2018-07-08,19.0,19,19,Mobile,between20and30,25.950,1.0,1,Fryup,North Yorkshire,North Yorkshire,England
32666,2018-08-13,13.0,13,13,Desktop and Laptop,between20and30,29.990,1.0,1,Maesgeirchen,Gwynedd,Gwynedd,Wales
32667,2018-07-19,13.0,13,13,Mobile,between20and30,22.950,1.0,1,Combe martin,Devon,Devon,England
32668,2018-08-13,17.0,17,17,Mobile,between40and50,46.950,NaN,1,Sunnyside,Rotherham,missing_county,missing_country
32669,2018-07-21,19.0,19,19,Mobile,between20and30,29.950,1.0,1,Thurlaston,Warwickshire,Warwickshire,England
32670,2018-08-10,17.0,17,17,Desktop and Laptop,between20and30,26.950,2.0,1,Deopham,Norfolk,Norfolk,England
32671,2018-07-23,10.0,10,10,Mobile,between20and30,21.950,1.0,1,Houston,Renfrewshire,missing_county,missing_country
32672,2018-07-31,21.0,21,21,Mobile,between20and30,21.950,1.0,1,Redding,Falkirk,Falkirk,Scotland
32673,2018-07-06,19.0,19,19,Mobile,lessThan10,1.990,1.0,1,Ardersier,Highland,missing_county,missing_country
32675,2018-08-03,18.0,18,18,Mobile,between10and20,19.950,2.0,1,Upton,Cheshire West And Chester,missing_county,missing_country
32676,2018-07-24,13.0,13,13,Mobile,between20and30,24.950,2.0,1,Debenham,Suffolk,Suffolk,England
32677,2018-08-04,15.0,15,15,Mobile,between20and30,29.950,1.0,1,Riccarton,Edinburgh,missing_county,missing_country
32678,2018-07-09,19.0,19,19,Mobile,between40and50,41.950,1.0,1,Coxhoe,Durham,missing_county,missing_country
32679,2018-07-26,12.0,12,12,Desktop and Laptop,between10and20,15.900,1.0,1,Broadway,Somerset,Somerset,England
32680,2018-07-12,11.0,11,11,Mobile,between20and30,24.500,1.0,1,Darfield,Barnsley,missing_county,missing_country
32681,2018-08-07,22.0,22,22,Mobile,between20and30,24.950,1.0,1,Torksey,Lincolnshire,Lincolnshire,England